---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.APP_NAME}}-service
  name: {{.APP_NAME}}-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: {{.APP_NAME}}
